# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad2cc05be72b036c2a4d29a3edffb3884b31b3a4e3a0e0290beab2aadd44184a64fa3988acd4ce7ee241ffe81e4973709a3c7abd3ce82b0961c81e8b2a49cad6

test:
  secret_key_base: 4bf324c6d75eb579f968a7d6d0e25a4157f010464b1e33e7b24a9eb027a9fda5f9c15aa7666fd9dfcf22597ab7c87d9f9704dde8524985f3e0b5bd907cefe1d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
